name: Example
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: swift
          args: |
            test
            build
